// Generated by dedot cli

import type { AccountId32 } from "dedot/codecs";

export type InkStorageLazyMapping = {};

export type DechatRoom = {
  id: bigint;
  name: string;
  messageCount: bigint;
  creator: AccountId32;
};

export type InkStorageTraitsImplsResolverKey = {};

export type InkStorageTraitsImplsAutoKey = {};

export type InkStorageTraitsImplsManualKey = {};

export type DechatMessage = {
  id: bigint;
  content: string;
  creator: AccountId32;
  createdAt: bigint;
};

export type Dechat = {
  rooms: InkStorageLazyMapping;
  roomCount: bigint;
  roomMessages: InkStorageLazyMapping;
  userRooms: InkStorageLazyMapping;
};

export type InkPrimitivesLangError = "CouldNotReadInput";

export type DechatError =
  | "Unauthorized"
  | "RoomExisted"
  | "RoomNotExisted"
  | "AlreadyJoined"
  | "MaxRoomReached"
  | "CannotAccess";

export type InkEnvNoChainExtension = null;
